<?php

namespace Database\Seeders\Admin;

use App\Models\Admin\SiteSections;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Constants\SiteSectionConst;
use Illuminate\Support\Str;

class SiteSectionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $site_sections = array(
            array('key' => 'site_cookie','value' => '{"status":true,"link":"https:\\/\\/www.appdevs.net\\/policy","desc":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."}','status' => '1','serialize' => NULL,'created_at' => '2023-11-15 08:40:53','updated_at' => '2023-11-15 08:40:53'),
            array('key' => 'glance-section','value' => '{"items":{"65548415c3afa":{"image":"","id":"65548415c3afa"},"65548415c3afd":{"image":"","id":"65548415c3afd"},"65548415c3afe":{"image":"","id":"65548415c3afe"},"65548415c3aff":{"image":"","id":"65548415c3aff"},"65548415c3b00":{"image":"","id":"65548415c3b00"}}}','status' => '1','serialize' => NULL,'created_at' => '2023-11-15 08:40:53','updated_at' => '2023-11-15 08:40:53'),
            array('key' => 'banner-section','value' => '{"button_link":"https:\\/\\/www.youtube.com\\/embed\\/7p6hG3plQj4?si=GdtHRzd7M2wXWRva","language":{"en":{"title":"New era of financial innovation","heading":"Make your Crypto Transaction","sub_heading":"Cryptocurrencies have introduced a new era of financial innovation, offering opportunities and challenges. As the technology continues to evolve, their impact on various industries.","button_name":"Explore Now"},"es":{"title":null,"heading":null,"sub_heading":null,"button_name":null}},"image":"seeder/banner.webp","button_image":"seeder/button.webp"}','status' => '1','serialize' => NULL,'created_at' => '2023-11-18 09:30:02','updated_at' => '2023-11-18 10:23:18'),
            array('key' => 'security-section','value' => '{"language":{"en":{"title":"Security System","heading":"More Ways To Security System"},"es":{"title":null,"heading":null}},"items":{"6558a3257093e":{"language":{"en":{"item_title":"Global Access For Site","item_heading":"Many cryptocurrencies have a fixed supply or a controlled issuance schedule."},"es":{"item_title":null,"item_heading":null}},"status":0,"id":"6558a3257093e","icon":"fas fa-address-book"},"6558a4718a0df":{"language":{"en":{"item_title":"Digital & Secure Payments","item_heading":"Many cryptocurrencies have a fixed supply or a controlled issuance schedule."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"6558a4718a0df","icon":"fas fa-adjust"},"6558a49e09dc9":{"language":{"en":{"item_title":"Decentralized Finance & NFTs","item_heading":"Many cryptocurrencies have a fixed supply or a controlled issuance schedule."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"6558a49e09dc9","icon":"fab fa-adn"},"6558a4bc71b43":{"language":{"en":{"item_title":"Free transactions & Support","item_heading":"Many cryptocurrencies have a fixed supply or a controlled issuance schedule."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"6558a4bc71b43","icon":"fab fa-affiliatetheme"},"6558a4dd00dbb":{"language":{"en":{"item_title":"SMS or Email Verification","item_heading":"Many cryptocurrencies have a fixed supply or a controlled issuance schedule."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"6558a4dd00dbb","icon":"fab fa-accusoft"},"6558a508187b8":{"language":{"en":{"item_title":"KYC Integration & Solution","item_heading":"Many cryptocurrencies have a fixed supply or a controlled issuance schedule."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"6558a508187b8","icon":"fab fa-android"},"6558a52936c33":{"language":{"en":{"item_title":"Two Factor Authentication","item_heading":"Many cryptocurrencies have a fixed supply or a controlled issuance schedule."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"6558a52936c33","icon":"fab fa-bitcoin"},"6558a54568d0d":{"language":{"en":{"item_title":"End-to-End Encryption","item_heading":"Many cryptocurrencies have a fixed supply or a controlled issuance schedule."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"6558a54568d0d","icon":"fas fa-bold"}}}','status' => '1','serialize' => NULL,'created_at' => '2023-11-18 11:16:19','updated_at' => '2023-11-19 04:24:51'),
            array('key' => 'download-app','value' => '{"image":"seeder/download-app.webp","language":{"en":{"title":"About us","heading":"The Way of the Wayfinding Mark","sub_heading":"Cryptocurrencies are not controlled by a central authority. Instead, they rely on distributed ledger technology (blockchain) to record and verify transactions. This decentralization eliminates the need for intermediaries like banks.\\r\\n\\r\\nWhile transactions are recorded on a public ledger, users\' identities are typically pseudonymous. This provides a level of privacy but has raised concerns about illegal activities."},"es":{"title":null,"heading":null,"sub_heading":null}},"items":{"65598cb7b470c":{"language":{"en":{"item_title":"Android"},"es":{"item_title":null}},"id":"65598cb7b470c","image":"seeder/app-play.webp","link":"https:\\/\\/play.google.com\\/store\\/games?hl=en&gl=US","created_at":"2023-11-19T04:19:03.749387Z"},"65598d0b5a9ea":{"language":{"en":{"item_title":"Apple"},"es":{"item_title":null}},"id":"65598d0b5a9ea","image":"seeder/app-play.webp","link":"https:\\/\\/www.apple.com\\/app-store\\/","created_at":"2023-11-19T04:20:27.377567Z"}}}','status' => '1','serialize' => NULL,'created_at' => '2023-11-19 04:18:22','updated_at' => '2023-11-19 07:11:48'),
            array('key' => 'statistic-section','value' => '{"image":"seeder/statistic.webp","language":{"en":{"title":"Overview","heading":"Last 15 years Crypto | Statistics","sub_heading":"Globally transition ours multidisciplinary applications for bleeding-edge vortals. harness o ours plug-and-plays networks without stand-alone bandwidth market harness competitive channels."},"es":{"title":null,"heading":null,"sub_heading":null}},"items":{"6559958679838":{"language":{"en":{"title":"Payment Gateway"},"es":{"title":null}},"id":"6559958679838","status":1,"counter_value":"10"},"6559967b82ef6":{"language":{"en":{"title":"Currencies"},"es":{"title":null}},"id":"6559967b82ef6","status":1,"counter_value":"10000"},"655996b348864":{"language":{"en":{"title":"Transactions Per Day"},"es":{"title":null}},"id":"655996b348864","status":1,"counter_value":"500000"}}}','status' => '1','serialize' => NULL,'created_at' => '2023-11-19 04:53:53','updated_at' => '2023-11-19 09:47:39'),
            array('key' => 'call-to-action-section','value' => '{"image":"seeder/call_to_action.webp","language":{"en":{"heading":"Got Some Questions? Feel Free to Ask Us!","sub_heading":"10 new offers every day. 350 offers on site, Trusted by a community of thousands of users.","button_name":"Contact Us"},"es":{"heading":null,"sub_heading":null,"button_name":null}}}','status' => '1','serialize' => NULL,'created_at' => '2023-11-19 05:51:21','updated_at' => '2023-11-19 05:51:21'),
            array('key' => 'footer-section','value' => '{"footer":{"language":{"en":{"description":"Cryptocurrencies have introduced a new era of financial innovation, offering opportunities and challenges."},"es":{"description":null}},"image":""},"social_links":[{"icon":"fab fa-facebook","link":"https:\\/\\/www.facebook.com\\/appdevsx"},{"icon":"fab fa-instagram","link":"https:\\/\\/www.instagram.com\\/"},{"icon":"fab fa-twitter","link":"https:\\/\\/twitter.com\\/?lang=en"},{"icon":"fab fa-github","link":"https:\\/\\/github.com\\/"}]}','status' => '1','serialize' => NULL,'created_at' => '2023-11-19 06:07:49','updated_at' => '2023-11-19 06:07:49'),
            array('key' => 'news-letter-section','value' => '{"language":{"en":{"title":"Newsletter","description":"Check Our Newsletter And Subscribe Us."},"es":{"title":null,"description":"Check Our Newsletter And Subscribe Us."}}}','status' => '1','serialize' => NULL,'created_at' => '2023-11-19 06:21:27','updated_at' => '2023-11-19 06:21:36'),
            array('key' => 'about-section','value' => '{"image":"seeder/about.webp","language":{"en":{"title":"About us","heading":"The Way of the | Wayfinding Mark","sub_heading":"Cryptocurrencies are not controlled by a central authority. Instead, they rely on distributed ledger technology (blockchain) to record and verify transactions. This decentralization eliminates the need for intermediaries like banks.\\r\\n\\r\\nWhile transactions are recorded on a public ledger, users\' identities are typically pseudonymous. This provides a level of privacy but has raised concerns about illegal activities."},"es":{"title":null,"heading":null,"sub_heading":null}}}','status' => '1','serialize' => NULL,'created_at' => '2023-11-19 07:14:59','updated_at' => '2023-11-19 09:49:58'),
            array('key' => 'faq-section','value' => '{"language":{"en":{"title":"FAQs","heading":"Frequently Asked | Questions"},"es":{"title":null,"heading":null}},"items":{"6559c95b744b2":{"language":{"en":{"question":"What is multi-currency account & how does it work?","answer":"Moreover general optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email."},"es":{"question":null,"answer":null}},"status":1,"id":"6559c95b744b2"},"6559c9d42216a":{"language":{"en":{"question":"What is multi-currency account & how does it work?","answer":"Moreover general optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email."},"es":{"question":null,"answer":null}},"status":1,"id":"6559c9d42216a"},"6559c9f007ed9":{"language":{"en":{"question":"What is the best features & services we deliver?","answer":"Moreover general optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email."},"es":{"question":null,"answer":null}},"status":1,"id":"6559c9f007ed9"},"6559ca3437d45":{"language":{"en":{"question":"What is the best features & services we deliver?","answer":"Moreover general optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email."},"es":{"question":null,"answer":null}},"status":1,"id":"6559ca3437d45"},"6559ca4057db8":{"language":{"en":{"question":"What Modes Of Payment Do You Accept?","answer":"Moreover general optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email."},"es":{"question":null,"answer":null}},"status":1,"id":"6559ca4057db8"},"6559ca582a454":{"language":{"en":{"question":"What Modes Of Payment Do You Accept?","answer":"Moreover general optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email."},"es":{"question":null,"answer":null}},"status":1,"id":"6559ca582a454"},"6559ca64d3ca4":{"language":{"en":{"question":"What happened to the borderless account?","answer":"Moreover general optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email."},"es":{"question":null,"answer":null}},"status":1,"id":"6559ca64d3ca4"}}}','status' => '1','serialize' => NULL,'created_at' => '2023-11-19 08:37:29','updated_at' => '2023-11-19 09:51:09'),
            array('key' => 'service-section','value' => '{"language":{"en":{"title":"Services","heading":"Our Upheld What We | Serve"},"es":{"title":null,"heading":null}},"items":{"6559d1bdec1e6":{"language":{"en":{"item_title":"Digital Payments","item_heading":"Cryptocurrencies can be used for online and in-person payments, offering an alternative to traditional payment methods."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"6559d1bdec1e6","icon":"fas fa-th-large"},"6559d25e7a3dd":{"language":{"en":{"item_title":"Global Access","item_heading":"Cryptocurrencies can be used for online and in-person payments, offering an alternative to traditional payment methods."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"6559d25e7a3dd","icon":"fas fa-print"},"6559d291cb562":{"language":{"en":{"item_title":"Remittances","item_heading":"Cryptocurrencies can be used for online and in-person payments, offering an alternative to traditional payment methods."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"6559d291cb562","icon":"fas fa-book-open"},"6559d2a6500c9":{"language":{"en":{"item_title":"Decentralization","item_heading":"Cryptocurrencies can be used for online and in-person payments, offering an alternative to traditional payment methods."},"es":{"item_title":null,"item_heading":null}},"status":1,"id":"6559d2a6500c9","icon":"fas fa-mobile"}}}','status' => '1','serialize' => NULL,'created_at' => '2023-11-19 09:12:40','updated_at' => '2023-11-19 09:34:12'),
            array('key' => 'blog-section','value' => '{"language":{"en":{"title":"Web Journal","heading":"Read Our Recent | Web Journal"},"es":{"title":null,"heading":null}}}','status' => '1','serialize' => NULL,'created_at' => '2023-11-19 10:49:17','updated_at' => '2023-11-19 11:25:43')
        );
        
        SiteSections::insert($site_sections,['key'],['value','status']);
    }
}
